version: '3.8'
services:
  emqx:
    image: emqx:5.8
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - ./emqx/log:/opt/emqx/log
      - ./emqx/data:/opt/emqx/data
    restart: always

  nginx:  
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: .Lyl41368
      MYSQL_DATABASE: iot_db_mysql
      MYSQL_USER: lyl41368
      MYSQL_PASSWORD: .Lyl41368
    restart: always
 
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root          #不要用root登录，因为不好用
      MONGO_INITDB_ROOT_PASSWORD: .Lyl41368    #不要用root登录，因为不好用
      MONGO_INITDB_DATABASE: iot_db_mongo
      MONGO_INITDB_USERNAME: lyl41368
      MONGO_INITDB_PASSWORD: .Lyl41368
    restart: always
